# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Article seeds


#User seeds
User.destroy_all
u1 = User.create :name => "Luke Eaton", :admin => true, :email => "lukeaton@gmail.com", :password => "chicken"
u2 = User.create :name => "Aviva Sleigh", :admin => false, :email => "dipsy@winky.com", :password => "chicken"
u3 = User.create :name => "Aaron Shaw", :admin => false, :email => "lala@winky.com", :password => "chicken"



Article.destroy_all
a1 = Article.create(title: "Steven Pinker’s Counter-Enlightenment", story: "A review of Enlightenment Now, by Steven Pinker. Viking (February 2018) 576 pages.


Every so often, something will unite individuals in outrage who disagree furiously about virtually everything else. For the moment, that something is Canadian psychologist Steven Pinker’s latest book, Enlightenment Now: The Case for Reason, Science, Humanism, and Progress. At the New York Times, conservative columnist Ross Douthat decried what he called Pinker’s “smug secular certainties,” and in the London Evening Standard, Melanie McDonagh declared that his “Whiggish case” ignored the “fruits of belief in [God]” and the “old problem of existential angst.” Meanwhile, in the left-leaning New Statesman, surly pessimist John Gray showered extravagant contempt over Pinker’s “evangelism of science” and “ideology of scientism,” and at ABC, Peter Harrison took exception to his “teleological view of history” and “misplaced faith in data, metrics and statistical analysis.”

It is worth noticing that Pinker’s most trenchant critics are eager to flaunt their aversion to the very values Pinker sets out to defend – reason, science, humanism, and progress – and that their critiques display the traits and tics of exactly the kind of counter-Enlightenment thinking he attacks. These counter-Enlightenment trends include Catholic, Romantic, and Postmodern modes of thought which stand – and have always stood – in opposition to the values that Pinker’s book credits with the vast advances humankind has made since the 18th Century.

Douthat’s review, entitled “The Edges of Reason,” claims that Pinker’s attempts to “defend Reason against its enemies . . . absolves his idealized version of the modern project of all imperial and eugenic and centralizing cruelties, and all the genocides and persecutions justified in Reason’s name.” He then offers a somewhat eccentric defence of prayer, ritual, and even alternative medicine, as “individual experimentation”:

Such individual experimentation is not the same thing as the scientific method; it lacks the proving tests of replication and consensus. But the two approaches are more closely related than today’s apostles of scientism often suggest. They proceed from the same intense curiosity, the same desire for understanding through experience — and personalized experimentation can be the only way to be empirical when your subject is the strange nexus of the self.

It’s hard to tell from such a short review if Douthat is just idly spitballing here, or if space constrains him from developing a genuinely thought-provoking line of discussion. In any event, Douthat mischaracterises Pinker’s point, which is simply that reason offers a demonstrably more effective means of understanding the world than revealed wisdom, superstition, or faith-based belief. This does not, of course, preclude the possibility that some may find prayer or wish-thinking therapeutic, and Pinker readily acknowledges the “sense of communal solidarity and mutual support” that religious organisations and secular communities are able to provide.

Criticisms of reason as a value fundamental to human progress are hardly new. In his 2005 book, Counter-Enlightenments, the Canadian political theorist Graeme Garrard argued that scepticism about ‘instrumental’ reason (the rational adoption of means to pursue ends), in particular, united a range of counter-Enlightenment philosophies. These thinkers held that the Enlightenment provided individuals with a conception of instrumental reason that, when misapplied, would result in either anarchic chaos or totalitarianism. Whilst few denounced reason outright (their own theories were the product of this faculty, after all), several influential counter-Enlightenment thinkers saw instrumental and individual reason as threats to the prevailing social order. The 18th Century German philosopher, J. G. Hamann, for example, believed that reason and other such “airy” notions distracted humans from earthly virtues. He urged philosophers to find meaning in what was natural and familiar, admiring ignorance and genius as fundamentally Christian values that were crucial to his notion of “Socratic greatness.”

Some of Hamann’s contemporaries, such as the Irish conservative Edmund Burke and French monarchist Joseph de Maistre, were wary of individual reason, and believed that only the collective wisdom generated over centuries provided a reliable form of trial-and-error. Tradition, they argued, was necessary to prevent individual and radical uses of instrumental reason delivering totalitarianism. French Jesuit priest Augustin Barruel warned against the excessive application of reasoning and philosophy in areas where they did not belong. This he called “philosophism,” which he described as:

…the error of every man who denies the possibility of any mystery beyond the limits of reason, of everyone who, discarding revelation in defence of the pretended rights of reason, Equality and Liberty, seeks to subvert the whole fabric of the Christian religion.

Criticisms like these suggest that several counter-Enlightenment thinkers were indeed opposed to reason itself rather than merely its misapplication, and were afraid of what it might inflame in a general populace better suited to the comforts of superstition and whimsy.

It should be no surprise, then, that many of Pinker’s critics betray a concomitant distrust of science, which manifests as stern objections to what they invariably call “scientism.” Douthat complains about “today’s apostles of scientism” and Gray declares Pinker to be “an evangelist for science – or, to be more exact, an ideology of scientism.” Here, “scientism” is a pejorative used to describe the ideological belief that science can settle all questions of import. This belief, it is feared, will be used to invade, sterilise, and finally displace the humanities and the arts, robbing us of the unique beauty and insight they provide. Peter Harrison, director of the Institute for Advanced Studies in the Humanities at the University of Queensland, suggests that the field of history will one day regard “misplaced faith in data, metrics and statistical analysis as a curse of the twenty-first century.”

This rather paranoid objection is not especially new either. Back in 1959, Pinker reminds us, the scientist and novelist C. P. Snow gave a series of important lectures, subsequently published as The Two Cultures and the Scientific Revolution. Snow postulated that the rise of a culture of science prizing objectivity was causing alarm among a ‘Second Culture’ that prizes subjectivity – literary intellectuals, cultural critics, and essayists. Snow found this alarm unnecessary and counter-productive, and he urged the Second Culture to embrace scientific understanding. In 1962, the literary critic F. R. Leavis wrote a furious response, during the course of which he emptied the same kind of scornful invective over Snow that Gray now empties over Pinker:

After noting Snow’s “utter lack of intellectual distinction and . . . embarrassing vulgarity of style,” Leavis scoffed at a value system in which “‘standard of living’ is the ultimate criterion, its raising an ultimate aim.” As an alternative, he suggested that “in coming to terms with great literature we discover what at bottom we really believe. What for—what ultimately for? What do men live by?—the questions work and tell at what I can only call a religious depth of thought and feeling.”

But Leavis misunderstood, misread, or misrepresented Snow then just as Gray and Harrison misunderstand, misread, or misrepresent Pinker now. Snow’s critics, like those who fret about scientism today, were unable or unwilling to think in anything other than zero-sum terms. Snow, on the other hand, recommended a positive-sum synthesis of science and the humanities that would be mutually enriching:

Snow, of course, never held the lunatic position that power should be transferred to the culture of scientists. On the contrary, he called for a Third Culture, which would combine ideas from science, culture, and history and apply them to enhancing human welfare across the globe. The term was revived in 1991 by the author and literary agent John Brockman, and it is related to the biologist E. O. Wilson’s concept of consilience, the unity of knowledge, which Wilson in turn attributed to (who else?) the thinkers of the Enlightenment.

In the same way, Pinker argues that evidence from a variety of methods can converge to produce fresh understanding in non-scientific fields. Linguistics, he points out, use both philosophy of mind and cognitive science to test new hypotheses and build knowledge. Undeterred, Gray protests that “science cannot underwrite any political project, classical liberal or otherwise, because science cannot dictate human values.” Gray’s apparent belief that this is a decisive refutation of some kind is particularly amusing, because Pinker – repeatedly! – says the same. “Science,” he writes, “is not enough to bring about progress,” and “scientific facts do not by themselves dictate values.”

Nor does Pinker absolve those who use the scientific method in the service of oppression and cruelty. “An endorsement of scientific thinking,” he writes, “must first of all be distinguished from any belief that members of the occupational guild called ‘science’ are particularly wise or noble.” It is humanism, he argues, which “provides the ought that supplements the is.”

Predictably, Pinker’s counter-Enlightenment critics are as unimpressed by the demonstrable merits of secular humanism as they are by those of reason and science. Pinker defines contemporary humanism as a movement with a non-supernatural basis for meaning and ethics, the goal of which is to maximise human flourishing and the wellbeing of other sentient organisms. At NYMag, the conservative Christian Andrew Sullivan chastised Pinker’s “contempt for religion,” and in The Nation, the historian David Bell griped about his “rigid, Richard Dawkins-style atheism.” But Pinker describes humanism as “by no means incompatible with religious institutions” and states “that religions should not be condemned or praised across the board.”

As the historian Darrin McMahon observed in his 2002 book, Enemies of the Enlightenment, a theme common to counter-Enlightenment thinkers (especially those who were Catholic) was the fear that the materialism and secularism of Enlightenment philosophy would diminish the necessity of faith, and that these philosophers were militant atheists determined to dismantle the church and monarchy. Interestingly, McMahon also demonstrates that this pervasive perception of the Enlightenment has been shaped retrospectively by various counter-Enlightenment writers, and suggests it is now “largely ignored” by academic scholars in the field due to its biases. In any case, many of the Enlightenment’s most important thinkers were not atheists, but deists and believers of one sort or another, who nevertheless held that quarrelling religions and their mutually exclusive doctrines and edicts should play no part in determining human ethics or governance.

In a bad-tempered review for the New York Times under the risible title, “Steven Pinker Wants You to Know Humanity Is Doing Fine. Just Don’t Ask About Individual Humans,” Jennifer Szalai denounces Pinker’s “crude utilitarian sentiments” and accuses him of being “sympathetic to humanity in the abstract but impervious to the suffering of actual human beings.” It would surely be impossible to assess human progress by examining the life of every human being, but what does humanity consist of, if not an aggregate network of actual individual human beings? Pinker justifies his use of aggregate data by pointing out that “a quantitative mindset, despite its nerdy aura, is in fact the morally enlightened one, because it treats every human life as having equal value rather than privileging the people who are closest to us or most photogenic.” Szalai’s response is to complain that:

Even if manufacturing jobs have gone to China, “and the world’s poor have gotten richer in part at the expense of the American lower middle class,” he still sees this as cause for celebration: “As citizens of the world considering humanity as a whole, we have to say that the trade-off is worth it.”

Szalai finds Pinker’s arguments, attitude, and even his marshalling of copious data, “disdainful and condescending.” But the painstaking care with which he makes his case for human progress is simply aimed at reducing what is known as the “Optimism Gap,” which occurs when people assume that their own living standards and quality of life are improving but that the standards of society in general are worsening. A ‘Negativity bias’ (“people dread losses more than they look forward to gains…dwell on setbacks more than they savor good fortune…are more stung by criticism than they are heartened by praise”) and the ‘Availability heuristic’ (“people estimate the probability of an event or the frequency of a kind of thing by the ease with which instances come to mind”) combine to produce a media culture that emphasises bad news at the expense of good (“if it bleeds it leads”) and disfigures our understanding of the world as it is.

“Intellectual culture,” Pinker observes, “should strive to counteract our cognitive biases, but all too often it reinforces them.” This, in turn, can have negative consequences on voting behaviour and public trust in institutions. At a time when populist demagogues are riding to power on narratives of despair and decline, it is particularly important that people remain alive to the benefits and the fragility of incremental progress. In a book filled with amazing statistics and factoids, this passage is among the most remarkable:

Thrillingly, the gift of longevity is spreading to all of humankind, including the world’s poorest countries, and at a much faster pace than it did in the rich ones. “Life expectancy in Kenya increased by almost ten years between 2003 and 2013,” Norberg writes. “After having lived, loved and struggled for a whole decade, the average person in Kenya had not lost a single year of their remaining lifetime. Everyone got ten years older, yet death had not come a step closer.” As a result, inequality in life expectancy, which opened up during the Great Escape when a few fortunate countries broke away from the pack, is shrinking as the rest catch up. In 1800, no country in the world had a life expectancy above 40. By 1950, it had grown to around 60 in Europe and the Americas, leaving Africa and Asia far behind. But since then Asia has shot up at twice the European rate, and Africa at one and a half times the rate. An African born today can expect to live as long as a person born in the Americas in 1950 or in Europe in the 1930s. The average would have been longer still were it not for the calamity of AIDS, which caused the terrible trough in the 1990s before antiretroviral drugs started to bring it under control.

As the bearer of these glad tidings, Pinker has received no thanks from his opponents. On the contrary, they appear to resent being asked to acknowledge this news. Harrison accuses Pinker of offering a faith-based “teleological view of history – the idea that historical events are destined to unfold inexorably in a single direction.” Szalai derides his “messianic anticipation” and even David Wootton, in an otherwise positive review for the TLS, raises a sceptical eyebrow at “Pinker’s assumption that progress can be projected indefinitely into the future.”

Unsurprisingly, similar charges of ‘facile optimism’ were also made against the Enlightenment’s philosophers, despite their circumspection about what lay ahead. As Garrard writes, “none believed that progress was inevitable, although most thought that it was likely, even though it would not be easy and could not be taken for granted.” Predictable though such charges may be, they must be irritating for the author of a book, the explicit purpose of which is to make a case against naive complacency in favour of conditional optimism.

The central theme of Enlightenment Now, to which Pinker returns over and over again, is that progress has been – and will continue to be – possible, provided that we combine reason, science, and humanism with our capacity for ingenuity and sympathy and a defence of benign institutions. “The Enlightenment belief in progress,” Pinker cautions at one point, “should not be confused with the 19th Century belief in mystical forces, laws, dialectics, struggles, unfoldings, destinies, ages of man, and evolutionary forces that propel mankind ever upward toward utopia.”

But many of Pinker’s critics are not simply objecting to the details of progress, they are hostile to the idea that progress has occurred at all. While this may be partly due to the Optimism Gap, the Negativity bias, and the Availability heuristic, there are hints that it may reflect a deeper anxiety – that progress, especially recent progress, directly undermines a belief on the radical Left and Right that worsening human conditions and societal decline demand institutional overhaul, insurrection, and revolutionary change.

Not only is the idea of progress repulsive to eco-pessimists who believe humans are despoiling the planet and plunging the world into irredeemable chaos, it is also anathema to anarchists and populists who would rather see the state burn to the ground than support incremental reform, and to ethnonationalists who believe liberal cosmopolitanism has brought Western civilisation to the verge of collapse. There are those who claim that the threats posed by radicalism and populism from the Left and the Right are exaggerated. But the middle ground between catastrophising and complacency feels particularly narrow at the moment, and it is necessary to identify threats early, if they are to be effectively resisted.

On this count, Pinker has come prepared. The reason he is always one step ahead of his critics is that the counter-Enlightenment arguments they rehearse are as old as the Enlightenment itself. The difference is that now the evidence is in. There are those who have grumbled that Enlightenment Now isn’t really about the Enlightenment at all, and in a sense they are right. This is not a work of philosophy but a work of social science. Those expending time and keystrokes angrily complaining that Pinker’s version of the Enlightenment does not accord with their preferred definition are missing the point. Pinker’s book is not a case for the Enlightenment that invites refutation, but a refutation of the arguments of the counter-Enlightenment which, it turns out, have been wrong all along.



Saloni Dattani is an MSc student in behaviour genetics at the University of London. You can follow her on Twitter @salonium", date: '16/05/1976', user_id: u1.id, image: 'https://d24fkeqntp1r7r.cloudfront.net/wp-content/uploads/2018/03/10090919/12001.jpg')

a2 = Article.create(title: "On Toxic Femininity", story: "Male lions can be monsters, murderous and focused. Toxic, if you will.

Given the opportunity, male lions will kill the kittens in a pride over which they have gained control. They commit infanticide, which brings the new mothers, freshly childless, back into estrous. The females are quickly impregnated. This, we can all agree, is disturbing behavior, and may make some people feel rather less pleased with lions.

Given the opportunity, the vast majority of modern human males would do no such thing.

Those who argue that men are inherently toxic are, ironically, making arguments that are biologically essentialist. And they are making them badly, at that. Evolution built humans, as it did lions. But humans have longer childhoods and greater generational overlap, share more ideas with greater complexity, and usually live in more stable social groups than do lions. In humans, evolution has given us the capacity to shape personality during development to a greater degree than in any other species. As such, and because few human cultures would tolerate such behavior, the vast majority of men would not and could not kill babies, nor rape their grieving mothers.

*     *     *

Over 30 years ago, I came of age as a female in LA. Being a young woman in LA means being watched—watched for deviations from the norm, for indications of future fame, for signs of weakness. Watched simply for how one looks. There are, unfortunately, many examples, recent and not, that point to LA’s most famous industry being a place where young women need to be on guard. I never aspired to the industry, but even just living in LA, the culture is omnipresent.

Two anecdotes should suffice. Walking alone in my sun-kissed west LA neighborhood one summer, I was approached by a man looking for extras for a beach scene in a movie. Before I had said a word, he told me where to go, how much I would be paid per day, and what would be expected of me: that I stand around in a bikini, among others similarly clad. I told him I was going to college. He literally looked me up and down, adopted a frown, and assured me that I did not need to go to college. Beach scenes were my future, and from there—who can say? Better beach scenes, presumably.

Second anecdote: One of my many part-time jobs in high school, along with scooping ice cream and renting out VHS tapes, was staffing high end catering events. Dressed in classic, tailored black and white, I carried platters of hors d’ouevres around during cocktail hour, and ferried plated entrees during table service. At indoor events, male attendees would often stop me to engage in small talk, and ask for my number. I wished that they wouldn’t, but I felt no risk. One night, though, I worked an event on the backlot of Universal Studios. A group unaffiliated with Hollywood had booked it for a no-expenses-spared fete, and I was to do the usual, except that I would have to cover more ground. The kitchen was further away, the guests more spread out, with no walls to contain them. Before table service, my co-workers and I made the rounds with our platters of bruschetta and cured meats. On this Hollywood backlot, though, the lack of walls proved dangerous. A young man—older than me but younger than 30—maneuvered me away from the crowd. There were many shadows, and he stood too close. He looked at me with predatory eyes. He backed me into a hedge, rubbed up against me. And I got away from him before it went any further.

That was toxic masculinity, before the phrase existed.

Yes, toxic masculinity exists. But the use of the term has been weaponized. It is being hurled without care at every man. When it emerged, its use seemed merely imprecise—in most groups of people, there’s some guy waiting for an opportunity to fondle a woman’s ass without her consent, put his hand where he shouldn’t, right? That’s who was being outed as toxic. Those men—and far, far worse—do exist. Obviously. But wait—does every human assemblage contain such men? It does not. This term, toxic masculinity, is being wielded indiscriminately, and with force. We are not talking imprecision now, we are talking thoroughgoing inaccuracy.

Most men are not toxic. Their maleness does not make them toxic, any more than one’s ‘whiteness’ makes one racist. Assume for the moment that we could agree on terms: Is maleness more highly correlated with toxic masculinity than is femaleness? Yes. Ipso facto—the term is about maleness, so men will display more of it than will women. The logical leap is then concluding that all men are toxic. The very communities where ‘toxic masculinity’ is being discussed most are the communities where the men are, in my experience, compassionate, egalitarian, and not at all toxic.

Calling good men toxic does everyone a deep disservice. Everyone except those who seek empowerment through victim narratives.

For the record: I am not suggesting that actual victims do not exist, nor that they do not deserve full emotional, physical, legal, medical, and other support. I also do not want to minimize the fact that most women, perhaps even all, have experienced unpleasantness from a subset of men. But not all women are victims. And even among those women who have truly suffered at the hands of men, many—most, I would hazard to guess—do not want their status in the world to be ‘victim.’

All of which leads us directly to a topic not much discussed: toxic femininity.

Sex and gender roles have been formed over hundreds of thousands of years in human evolution, indeed, over hundreds of millions of years in our animal lineage. Aspects of those roles are in rapid flux, but ancient truths still exist. Historical appetites and desires persist. Straight men will look at beautiful women, especially if those women are a) young and hot and b) actively displaying. Display invites attention.

Hotness-amplifying femininity puts on a full display, advertising fertility and urgent sexuality. It invites male attention by, for instance, revealing flesh, or by painting on signals of sexual receptivity. This, I would argue, is inviting trouble. No, I did not just say that she was asking for it. I did, however, just say that she was displaying herself, and of course she was going to get looked at.

The amplification of hotness is not, in and of itself, toxic, although personally, I don’t respect it, and never have. Hotness fades, wisdom grows— wise young women will invest accordingly. Femininity becomes toxic when it cries foul, chastising men for responding to a provocative display.

Where we set our boundaries is a question about which reasonable people might disagree, but two bright-lines are widely agreed upon: Every woman has the right not to be touched if she does not wish to be; and coercive quid pro quo, in which sexual favors are demanded for the possibility of career advancement, is unacceptable. But when women doll themselves up in clothes that highlight sexually-selected anatomy, and put on make-up that hints at impending orgasm, it is toxic—yes, toxic—to demand that men do not look, do not approach, do not query.

Young women have vast sexual power. Everyone who is being honest with themselves knows this: Women in their sexual prime who are anywhere near the beauty-norms for their culture have a kind of power that nobody else has. They are also all but certain to lack the wisdom to manage it. Toxic femininity is an abuse of that power, in which hotness is maximized, and victim status is then claimed when straight men don’t treat them as peers.

Creating hunger in men by actively inviting the male gaze, then demanding that men have no such hunger—that is toxic femininity. Subjugating men, emasculating them when they display strength—physical, intellectual, or other—that is toxic femininity. Insisting that men, simply by virtue of being men, are toxic, and then acting surprised as relationships between men and women become more strained—that is toxic femininity. It is a game, the benefits of which go to a few while the costs are shared by all of us.

*     *     *

I had a student on one of my study abroad trips who had a perennial problem with clothing. She was never wearing enough of it. She was smart, athletic, and beautiful, but also intent on advertising hotness at all moments. At a field station in a jungle in Latin America, she approached me to complain that the local men were looking at her. The rest of us were wearing field gear—a distinctly unrevealing and unsexy garb. She was in a swimsuit. “Put on more clothes,” I told her. She was aghast. She wanted me to change the men, to talk to them about where to point their eyes. Here in their home, where we were visitors, and one of the gringos had shown up nearly naked, she wanted the men to change.

For a spell before that, my job was to trek around tropical forests studying poison frogs. I was interested in their sex lives, in figuring out how they choose their mates and their territories, in how they parent, and in what that meant about the evolution of sociality more generally.

My research revealed, in part, how many different ways there are to be territorial, and to be successful, in male frogs. In Madagascan poison frogs, there are multiple routes to success, both naturally and sexually selected—males can succeed, evolutionarily, by holding high-quality territories, and they can also succeed by having no territories at all (but by being rather more sneaky). Wide variance in strategy, and shifting strategies under different conditions, is well studied in animal behavior and game theory.

Given that we know this to be true in non-human animals, why would we imagine that humans are less, rather than even more, flexible? There are many ways to be female, and many ways to be male, and some of each are bad news for everyone but the individual employing them. As a social species that has become the dominant ecological force on our planet, we can and should aspire to behave in ways that are not merely selfish, not merely competitive, but also collaborative. Toxic masculinity, and toxic femininity, are inherently selfish modes, and those not employing them should be interested in seeing them eradicated.

*     *     *

The movement that has popularized the term ‘toxic masculinity’ shares tools and conclusions with those who see signs of ‘white supremacy’ everywhere they look. Intersectionalists have in common with one another a particular rhetorical trick: Any claim made by a member of an historically oppressed group is unquestionably true. Questioning claims is, itself, an act of oppression.

This opens the door for anyone who is willing to lie to obtain power. If you cannot question claims, any claim can be made.

Thus: Racism is ubiquitous. And all men are toxic. I object—but objection is not allowed. Everyone who understands game theory knows how this game ends: Innocent people being vilified with false claims, and exposed to witch hunts. Sexual assault is real, but that does not mean that all claims of sexual assault are honest.

It is shocking that this bears saying, but there is a world of men who are smart and compassionate and eager to have vibrant, surprising conversations with other people, both men and women. The sex-specific toxicity that I have seen, when it has been obvious, has mostly been in the other court. All men are toxic and all women victims? No. Not in my name.



Heather E. Heying is a former professor of evolutionary biology at The Evergreen State College. She has a PhD in Biology from the University of Michigan, and is the author of Antipode, an investigation of life and research in Madagascar. You can follow her on Twitter @HeatherEHeying", date: '18/09/1918', user_id: u1.id, image: 'https://d24fkeqntp1r7r.cloudfront.net/wp-content/uploads/2018/07/08185430/1200lioness.jpg')

a3 = Article.create(title: "The Birth of the Narcissism Revolution", story: "Editor’s note: the following is an extract of Selfie: How We Became So Self-Obsessed and What It’s Doing to Us, The Overlook Press; 1 edition (March 27, 2018), 416 pages.

In the months leading up to his death, in 1970, the humanistic psychologist Abraham Maslow began worrying about his legacy. He’d been preparing to write a critique of Esalen ‘and its whole chain’. One of the issues he’d become concerned with was self-esteem. Maslow was famous, most of all, for his hugely influential ‘Hierarchy of Needs’, which said that people are motivated to fulfill certain psychological appetites. At the top of his pyramid was ‘actualization’, which was extremely difficult and had, he thought, only been achieved by a few. But just beneath that was ‘esteem’. It seems that Maslow had been carrying out some tests on high-esteeming people that had been the cause of some concern: ‘High scorers in my test of dominance feeling, or self-esteem, were more apt to come late to appointments with the experimenter, to be less respectful, more casual, more forward, more condescending, less tense, anxious and worried, more apt to accept an offered cigarette, much more apt to make themselves comfortable without bid-ding or invitation.’

He wasn’t the only Human Potential guru who’d apparently come to a place of doubt late in life. According to Dr William Coulson, the chief of staff at Rogers’ Western Behavioral Sciences Institute, ‘After several years in California, Carl got so tired of having aspirants arrive at our door with no intention or ability to WORK that he sent out a letter. It said, in fact, “Less self-esteem, please. More self-discipline.”’

In December 1973, Esalen hosted a conference in San Fran- cisco called ‘Spiritual and Therapeutic Tyranny: The Willingness to Submit’. The Institute’s co-founder, Michael Murphy, had grown troubled, both by his observations of a cultish, guru-worshipping aspect that was developing in some quarters and also by new commercialized forms of personal transformation workshops, such as EST, which took place over two weekends and combined Esalen-style Human Potential thinking with a sales seminar format more familiar in an earlier period of America’s history. EST was created in 1971 by Werner Erhard, an Esalen graduate and student of both Carl Rogers and Abraham Maslow, who had also been a fan of a Dale Carnegie course he’d attended. Erhard, writes Truett, ‘Americanized the human potential movement in a way that Esalen had never done or tried to do.’ It was an instant success: fifty thousand people took the workshop in its first four years and it ended up boasting celebrity attendees including John Denver, Cher and Peter Gabriel. It represented a kind of business-ification of Human Potential methods that Murphy hoped to distance Esalen from with his conference.

It didn’t go well. Despite being organized by a mostly female committee, all twenty-six speakers were male – which led to protests, outside the venue, by feminists from Esalen’s San Francisco office. A journalist covering the event, Peter Marin of Harper’s Magazine, described the crowd of several hundred attendees as ‘restless, impatient, volatile; one could feel rising from it a palpable sense of hunger, as if these people had somehow been failed by both the world and their therapies.’ They had come to the conference, he wrote, for the same reason they had attended the workshops: ‘to find help. The human potential movement had still not done for them what it had promised, their lives had remained the same or perhaps worsened, and the new world, the promised transformation, seemed very slow in coming.’ As the event ground on, the audience barracked the panelists and the panelists shouted at each other. In his keynote address, the writer Sam Keen pointed out, devastatingly, that the ‘usually male, privileged’ leaders of the movement had hardly demonstrated, in their own selves, the efficacy of what they preached. ‘The best therapist turns out to have a clay heart. And Fritz was a dirty old man. And Freud couldn’t give up cigars. And Bill Schutz doesn’t jump for joy.’ It was a criticism redolent of an observation made by a former lover of Michael Murphy, who had himself suffered lifelong mental-health problems: ‘He got a million dollars’ worth of advice from some of the best psychologists in the country. None of it helped.’

Peter Marin’s report on the conference would end up being part of a cover story for Harper’s, published in October 1975. He captured what happened when Christian introspection met Human Potential’s belief that perfection, not evil, lay in our souls. The speakers, wrote Marin, exhibited ‘a tyrannical refusal to acknowledge the existence of a world larger than the self’ and when the audience questioned the panellists, ‘the questions they asked were invariably concerned with themselves, were about self-denial or self-esteem, all centred on the ego, all turned inwards’. The Human Potential Movement had posed the Western self a question: if God is inside all of us, then doesn’t it naturally follow that we are all Gods? Now the Western self had given its answer. Marin called his story ‘The New Narcissism’. It described the stunning darkness of Esalen’s conviction that, as gods, all humans have complete responsibility for everything that happens to them, even including the Jews that ‘burned’ in the Holocaust. When Marin asked one counsellor, at the institute, whether we owe anything to a child starving in the African desert, she snapped angrily back at him, ‘What can I do if a child is determined to starve?’

Ten months later, America’s chief chronicler of culture, Tom Wolfe, would author his own cover story on the subject, this time in New York Magazine. He named Esalen ‘Lemon Session Central’ and described the programmes of Fritz and Schutz in wild and cynical terms. ‘Outsiders, hearing of these sessions, wondered what on earth their appeal was,’ he wrote. ‘Yet the appeal was simple enough. It is summed up in the notion: “Let’s talk about Me.” No matter whether you managed to renovate your personality through encounter sessions or not, you had finally focused your attention and your energies on the most fascinating subject on earth: Me.’ Wolfe’s piece was called ‘The “ME” Decade’.

The old-age concerns of Maslow and Rogers had come too late. Their bright ideas had run out of control. But this feel-good American revolution, in which the interior self was recast as holy, and took responsibility for everything that happened to it, would turn out to be perfect for the coming times. In the 1970s and 1980s, as the economy underwent new, dramatic changes, the English-speaking nations became feverish with the idea that all of society’s problems, from unemployment to child abuse to domestic violence, could be solved by teaching the people to believe in their authentic, godlike selves. This harsh new world would be no place for ‘fakes’ or ‘shitheads’ or ‘weepers’. Everyone was special, and had what it took to thrive. All they had to do was believe.

One of the invited speakers, at Esalen’s terrible conference, was an imposing and angry politician with a deep, wounded-bear voice, who’d had his life changed partly by his experiences at the Institute, having first visited in 1962. He would help take Esalen’s stated mission – ‘that all men somehow possess a divine potentiality; that ways may be worked out – specific, systematic ways – to help, not the few, but the many toward a vastly expanded capacity to learn, to love, to feel deeply, to create’ – into the 1980s and beyond . . . into schools and prisons and courts; into government policy and around the world. He too would be dogged by the imperishable charge that all he was doing was indulging and encouraging narcissism.

He was a reformed Catholic, a disciple of Carl Rogers, an Esalen alumnus and soon to become one of the most powerful men in California. He was John ‘Vasco’ Vasconcellos and the mission of his life would be to give the world self-esteem.



Will Storr is a journalist, novelist and photographer. His features have appeared in numerous newspapers, including the Guardian, Times and Observer. Selfie: How We Became So Self-Obsessed and What It’s Doing to Us is now available on Amazon.", date: '01/01/2001', user_id: u1.id, image: 'https://d24fkeqntp1r7r.cloudfront.net/wp-content/uploads/2018/06/13060609/ravi-roshan-568880-unsplash-e1528869982937.jpg')

a4 = Article.create(title: "Libel of Jordan Peterson A Story of Journalistic Failure", story: "On Friday, a left-leaning Jewish magazine, the Forward, published an article by Ari Feldman titled “Is Jordan Peterson Enabling Jew Hatred?” accompanied by a picture of Adolf Hitler giving the Nazi salute next to Peterson. The Forward explains Vox-style: “Jordan Peterson is a public intellectual adored by neo-Nazis, white supremacists and conspiracy theorists. The neo-Nazi website the Daily Stormer called [him] ‘The Savior of Western Civilization.’”

What did Peterson do to become, according to the Forward, comparable to Hitler? In a recent blog post addressing anti-Semitism in the alt-right, Peterson “attributed [Jewish] influence to Jewish intelligence—an old anti-Semitic dog whistle”Lipstadt said that Peterson’s statements on Jewish intelligence reminded her of Kevin MacDonald, a professor of psychology who the Southern Poverty Law Center has described as “the neo-Nazi movement’s favorite academic.” MacDonald has written several books criticizing Jewish intellectual culture. (Peterson links to a critique of one of MacDonald’s books at the end of his blog post on Jewish intelligence.) Lipstadt said that MacDonald’s academic language obscures the anti-Semitism behind his opinions. She worries the same is true of Peterson.

Ari Feldman appears to be completely unaware of why Peterson took up the issue of anti-Semitism at this moment, why he attributed “alleged” Jewish influence to IQ, and what this has to do with Kevin MacDonald. Although this story is familiar to many Quillette readers, I recount it here.

On March 10, University of Oxford graduate student Nathan Cofnas published an academic paper criticizing the theories of Kevin MacDonald. MacDonald explains Jewish overrepresentation in liberal political movements with the theory that Judaism is a “group evolutionary strategy.” In pursuit of their group evolutionary strategy, Jewish intellectuals supposedly work to undermine white-gentile culture to improve the relative position of Jews.

Cofnas proposed an alternative theory, which he called the “default hypothesis”: “Because of their above-average intelligence and concentration in influential urban areas, Jews in recent history have been overrepresented in all major intellectual and political movements, including conservative movements, that were not overtly anti-Semitic.” Cofnas documented numerous examples of distorting history and misrepresenting sources in MacDonald’s work, and argued that the evidence favors the default hypothesis rather than MacDonald’s conspiracy theory.

Jordan Peterson was one of the first prominent people to promote Cofnas’s paper, and to brave the backlash from the anti-Semitic mob. On March 11 he tweeted it, writing: “A straightforward explanation for the high proportion of Jewish people among intellectuals (and necessary critique of a competing account).” (Other prominent people who promoted Cofnas’s paper included Steven Pinker and Christina Hoff Sommers.) Nazi apologists and MacDonald acolytes attacked Peterson on Twitter.


Steven Pinker
✔
@sapinker
 The Alt-Right embraces the bizarre anti-Semitic conspiracy theory that Jewish intellectuals advance Jewish interests with theories that undermine Christian culture. Nathan Cofnas refuted the idea & now responds to a reply by its major proponent.  https://geneticliteracyproject.org/2018/04/16/analyzing-kevin-macdonalds-culture-of-critique-and-the-alt-rights-embrace-of-anti-jewish-ideology/ …

2:13 AM - Apr 20, 2018

Analyzing Kevin MacDonald's 'Culture of Critique' and the alt-right's embrace of anti-Jewish...
he biblical commentator Rashi observes that in order for a falsehood to be successful, it has to contain at least some element of truth. According to one

geneticliteracyproject.org
262
217 people are talking about this
Twitter Ads info and privacy
So what did he do? A week later he tweeted a follow-up article by Cofnas and me. And on March 23rd he wrote the blog post where he addressed anti-Semites as follows: “So, what’s the story? No conspiracy. Get it? No conspiracy. Jewish people are over-represented in positions of competence and authority because, as a group, they have a higher mean IQ.”

Here’s the thing: Peterson is right. The average IQ of Ashkenazi Jews is the highest of any ethnic group in the world. Maybe there’s a controversy about the causes of group differences in IQ (though experts agree that IQ is highly heritable), but there’s no serious controversy about the fact that Jews have a high IQ. That’s a fact, not an “anti-Semitic dog whistle.”

Let’s review what happened: A Jewish academic wrote a paper criticizing Kevin MacDonald, who is the most popular intellectual in the world among anti-Semites. Jordan Peterson promoted the paper that criticized MacDonald, and when he received pushback from anti-Semites, he doubled down and insisted that the anti-Semites were wrong. Then the Forward came along and declared that Peterson was engaged in “anti-Semitic dog whistl[ing],” and put a picture of him next to Hitler.

You can’t make this stuff up.

The attack on Peterson by the Forward was click-bait disguised as reporting.  This new genre of “news” combines fake outrage by authors and masochistic curiosity by readers who lack the time or discipline to do proper research.  Like the SPLC, the Forward has lost all credibility by equating unorthodox thinkers with common bigots.



Jonathan Anomaly is a faculty fellow at the University of Gothenburg’s Center for Collective Action and Antimicrobial Resistance for the summer of 2018. ", date: '16/05/1976', user_id: u1.id, image: 'https://www.dailydot.com/wp-content/uploads/2018/08/jordan-peterson-talking.jpg')


a5 = Article.create(title: "WHY THE UNSPONSORED GUY IS SURFING’S NEW SUPERSTAR", story: "


Share
Being. Paid. To. Surf. The concept is still as ludicrous as it sounds, especially so when it’s not you who’s being paid. But what a bunch of jerks, really. Sticker boys with monster trucks full of cash being paid to catch two waves out of every set, fading blokes who’ve been surfing this place all their lives and who’ve just crawled out of a coalmine after a 12-hour shift ripping coal out with their bare hands. Sticker boys: corpos, microchipped, soulless, doing it for the money, ruining surfing for everyone the lot of ’em. Wankers.

When the surf industry was flying like Neville Bartos back in the early millennium, the bastards were everywhere. They’d run down the beach and you couldn’t even see their board for all the stickers on it. Surf sponsor, board sponsor, wax sponsor, undie sponsor, lawnmowing sponsor, fried chicken sponsor. And did you know their contract actually tells them where each sticker has to go? And do you know they actually paid a guy to put the stickers on for them? Wankers.

But fast forward to today and the greatest surfer of all time has a white board, whole surf teams are getting dumped by email, and when you open the real estate guide and think that bloke in the bad suit looks familiar then it’s probably because he once made the quarters at Figueira da Foz in 1996. The asteroid that hit the surf industry also created a mass extinction event of pro surfers. And you know what? As hard as it is to believe, we’re now actually starting to feel sorry for them. In this cynically crazed and contrarian world the unsponsored guy is the new surfing superstar.

Actually, being unsponsored right now might be the best thing to ever happen to your surfing career. Whole online campaigns are being run to get previously sponsored guys sponsored again. Entire surfing events are being run exclusively for unsponsored guys. You can’t turn on the Internet without being hit with some hard luck story from someone who used to be the luckiest person in the world until surf companies stopped sending them their free money and gave it to a 12-year-old instead.

Laurie Towner is the World Champ of unsponsored surfers. When the music stopped at Billabong contract time last year there was no chair – and no sticker – for the big guy. He and good mate, Wade Goodall became the poster boys for the unstickered generation, largely because a) they rip, and b) they’re a pair of effing legends. Suddenly people were screaming, “Can you believe these guys can’t get a sponsor?”…  people who didn’t even know who they were back when they were sponsored.

While their fans raged there was little animosity from the boys themselves – no online venting, no birds to the surf industry – they accepted it for what it was and started on the next chapter of their lives. It was a credit to them. Like anything good in the world they saw being paid to go surfing for what it is, a privilege, not a right. Even better, they’d seen the writing on the wall a year early and used their last year of a surfing paycheque to go mad, towing each other into the waves of their lives at Shipsterns and Chopes. Their whole last year on contract was like muck-up day at school. At the end of it they went back to their hometowns and their freshly-hatched grommets and back to a new life.

Believe it or not being a sponsored surfer is still a job, and if you ask anyone who leaves a long-term job anywhere, doing anything, what the first day of their new life feels like and they’ll give you one word – liberating. Despite the one minor drawback – nobody’s paying you – the world’s your oyster. You’re suddenly your own boss again, you wake up at 4am with a head full of ideas, and there’s no better motivator in the world than a young family and no regular paycheque. And for the unsponsored surfer today, you also pick up the kind of online cult following you could never have got when you were stickered up.

At the end of the day Laurie realised that being paid to surf is a dream, but you gotta wake up some day to reality and the reality you wake up to might not be all that bad after all. He’s back in Angourie, his little grom is doing surf checks with him, the snapper are on the chew, he’s been swinging a hammer in between swells, he’s done stunt work for the big pictures and absolutely nailed 20-foot Cloudbreak last week. Seems like he’s landed all right on them big feet of his.", date: '16/05/1976', user_id: u1.id, image: 'http://nnimgt-a.akamaihd.net/transform/v1/crop/frm/UPAcJLQNVGftX3BUDy544C/721a7d9c-cff1-44bc-b59c-e4bd5383d1ee.jpg/r7_0_3143_1757_w1200_h678_fmax.jpg')
